# Generated by Django 5.2.7 on 2025-10-25 19:50

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('year', models.IntegerField(validators=[books.models.validate_year], verbose_name='Год издания')),
                ('janr', models.CharField(default='Роман', max_length=50, verbose_name='Жанр')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'unique_together': {('title', 'author', 'year', 'janr')},
            },
        ),
    ]
